export const kernels = [
  'Linux version 6.8.0-arch1-1 (build@archlinux) (gcc 14.2.1) #1 SMP PREEMPT_DYNAMIC',
  'Command line: BOOT_IMAGE=/boot/vmlinuz-linux root=UUID=a1b2c3d4 rw quiet splash',
  'x86/fpu: x87 FPU will use FXSAVE',
  'ACPI: Local APIC address 0xfee00000',
  'ACPI: 6 ACPI AML tables successfully acquired',
  'PCI: BIOS Bug: MCFG area at e000 not reserved in ACPI',
  'pci 0000:00:00.0: [8086:2e30] type 00 class 0x060000',
  'pci 0000:00:02.0: [8086:2e32] type 00 class 0x030000',
  'pci 0000:00:1a.0: EHCI: BIOS handoff failed',
  'ENERGY_PERF_BIAS: Set to normal',
  'clocksource: tsc: mask: 0xffffffffffffffff max_cycles: 0x1d8',
  'Freeing SMP alternatives memory: 40K',
  'SMP: Total of 8 processors activated',
  'smpboot: CPU0: Intel Xeon E3-1230 v3 (family: 0x6 model: 0x3c)',
  'mce: CPU0: Thermal monitoring enabled',
  'PCI: 46 PCI devices found, 5 VGA devices',
  'pci 0000:01:00.0: vgaarb: VGA device added',
  'svc: VMware vSockets: successfully loaded',
  'serio: i8042 keyboard controller connected',
  'rtc_cmos 00:03: RTC can wake from S4',
  'input: AT Translated Set 2 keyboard as /devices/platform/i8042/serio0',
  'usb 1-1: new high-speed USB device number 2 using ehci-pci',
  'EDAC sbridge: Seeking for memory errors',
  'ata1: SATA link up 6.0 Gbps',
  'scsi 0:0:0:0: Direct-Access ATA Samsung SSD 870 2B6Q',
  'EXT4-fs (sda2): mounted filesystem with ordered data mode',
  'kvm: already loaded, disabling virtualization',
  'loop0: detected capacity change from 0 to 8',
  'usbcore: registered new interface driver usbhid',
  'hid-generic 0003:046D:C077.0001: input: USB HID v1.11 Mouse',
  'IPv6: ADDRCONF(NETDEV_UP): enp0s3: link is not ready',
  'e1000: enp0s3 NIC Link is Up 1000 Mbps Full Duplex',
  'NET: Registered protocol family 17',
  'audit: initializing netlink socket',
  'selinux: initialized (dev sda2, type ext4)',
  'Bluetooth: Core ver 2.22',
  'ath5k: ar2425: registered as ieee80211 phy0',
  'iwlwifi: loaded firmware version 77.2e9d3f6b.0',
  'tpm_tis: 1.2 TPM (device ID 0x3204)',
  'random: crng init done',
  'EDAC: MC0: Giving out device',
  'cpufreq: intel_pstate registered',
  'iTCO_vendor_support: vendor-support=0',
  'dmesg: printk: console enabled',
  'ACPI: button: Power Button (FF) registered',
  'nvme nvme0: 8 NVMe namespaces',
  'pcieport 0000:00:1c.5: AER: enabled',
];

export const systemdServices = [
  ['systemd', 'systemd', [
    'Starting Journal Service...',
    'Reached target Local File Systems',
    'Starting Remount Root and Kernel File Systems...',
    'Started Remount Root and Kernel File Systems',
    'Starting Load Kernel Modules...',
    'Started Load Kernel Modules',
    'Starting Apply Kernel Variables...',
    'Started Apply Kernel Variables',
    'Mounting POSIX Message Queue File System...',
    'Mounted POSIX Message Queue File System',
    'Starting Create Static Device Nodes...',
    'Started Create Static Device Nodes',
    'Reached target Preparation for Local File Systems',
    'Starting udev Kernel Device Manager...',
    'Started udev Kernel Device Manager',
    'Starting udev Coldplug all Devices...',
    'Started udev Coldplug all Devices',
    'Starting Network Configuration...',
    'Started Network Configuration',
    'Reached target Network',
    'Starting Permit User Sessions...',
    'Started Permit User Sessions',
    'Starting AR3LYX1 System Services...',
    'Started AR3LYX1 System Services',
    'Reached target Multi-User System',
    'Started AR3LYX1 Node.js Backend',
    'Started AR3LYX1 PostgreSQL Service',
    'Reached target Graphical Interface',
    'Started Update UTMP about System Runlevel Changes',
    'systemd: Startup finished in 2.481s',
  ]],
  ['NetworkManager', 'NetworkManager', [
    'NetworkManager: <info> scanning for WiFi networks',
    'NetworkManager: <info> connected to "AR3LYX1-Net"',
    'NetworkManager: <info> IPv4 configuration: dhcp',
    'NetworkManager: <info> address 192.168.1.42/24',
    'NetworkManager: <info> gateway 192.168.1.1',
    'NetworkManager: <info> DNS: 8.8.8.8, 1.1.1.1',
  ]],
  ['sshd', 'sshd', [
    'sshd: server listening on 0.0.0.0 port 22',
    'sshd: server listening on :: port 22',
    'sshd: re-exec requires execution with same path',
  ]],
  ['auditd', 'auditd', [
    'auditd: dispatcher started',
    'auditd: backlog limit set to 8192',
    'auditd: processing audit events',
  ]],
  ['cron', 'cron', [
    'cron: (root) CMD (run-parts /etc/cron.hourly)',
    'cron: (ar3lyx1) CMD (/opt/ar3lyx1/healthcheck.sh)',
    'cron: (ar3lyx1) CMD (/opt/ar3lyx1/sync-events.sh)',
  ]],
  ['backend', 'backend', [
    'AR3LYX1-backend: loading configuration from /etc/ar3lyx1/config.yml',
    'AR3LYX1-backend: connecting to PostgreSQL on localhost:5432',
    'AR3LYX1-backend: database pool initialized (max: 20)',
    'AR3LYX1-backend: starting Express server on port 3000',
    'AR3LYX1-backend: Portfolio API ready',
    'AR3LYX1-backend: WebSocket server listening for live events',
    'AR3LYX1-backend: cache warming completed (4 modules loaded)',
    'AR3LYX1-backend: AR3LYX1 portfolio v1.0.0 initialized',
  ]],
];
