import type { Certification } from '../domain/certification';

const certificationsData: Certification[] = [
  // ── Technical ──
  {
    id: 'aws-solutions-architect',
    title: 'AWS Solutions Architect',
    issuer: 'Amazon Web Services',
    description: 'Design and deploy scalable, highly available, and fault-tolerant systems on AWS.',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80',
    tags: ['AWS', 'Cloud', 'Architecture'],
    category: 'technical',
    issuedAt: '2025-11-15',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'gcp-professional',
    title: 'Google Cloud Professional',
    issuer: 'Google Cloud',
    description: 'Expertise in designing and managing Google Cloud solutions with security and reliability.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80',
    tags: ['GCP', 'Cloud', 'DevOps'],
    category: 'technical',
    issuedAt: '2025-09-20',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'azure-admin',
    title: 'Microsoft Azure Administrator',
    issuer: 'Microsoft',
    description: 'Manage Azure subscriptions, secure identities, and configure virtual networking.',
    image: 'https://images.unsplash.com/photo-1633419461186-7d40a38105ec?w=600&q=80',
    tags: ['Azure', 'Cloud', 'Infrastructure'],
    category: 'technical',
    issuedAt: '2025-07-10',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'comptia-security-plus',
    title: 'CompTIA Security+',
    issuer: 'CompTIA',
    description: 'Core cybersecurity skills covering threats, vulnerabilities, cryptography, and risk management.',
    image: 'https://images.unsplash.com/photo-1555949963-aa79dcee981c?w=600&q=80',
    tags: ['Security', 'Cybersecurity', 'Risk'],
    category: 'technical',
    issuedAt: '2025-05-22',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'cisco-ccna',
    title: 'Cisco CCNA',
    issuer: 'Cisco',
    description: 'Install, configure, and troubleshoot medium-size routed and switched networks.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80',
    tags: ['Networking', 'Cisco', 'Routing'],
    category: 'technical',
    issuedAt: '2025-03-14',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'kubernetes-cka',
    title: 'Kubernetes CKA',
    issuer: 'CNCF',
    description: 'Administer Kubernetes clusters, manage workloads, and configure networking and storage.',
    image: 'https://images.unsplash.com/photo-1667372393119-5d4c48d07dc9?w=600&q=80',
    tags: ['Kubernetes', 'Containers', 'Orchestration'],
    category: 'technical',
    issuedAt: '2025-01-30',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'mongodb-developer',
    title: 'MongoDB Developer',
    issuer: 'MongoDB University',
    description: 'Design, query, and optimize applications using MongoDB document data model.',
    image: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&q=80',
    tags: ['MongoDB', 'Database', 'NoSQL'],
    category: 'technical',
    issuedAt: '2024-12-05',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'lpic-1',
    title: 'Linux Professional LPIC-1',
    issuer: 'Linux Professional Institute',
    description: 'Manage Linux systems, including command-line operations, security, and maintenance.',
    image: 'https://images.unsplash.com/photo-1629654297299-c8506221ca97?w=600&q=80',
    tags: ['Linux', 'SysAdmin', 'DevOps'],
    category: 'technical',
    issuedAt: '2024-10-18',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'terraform-associate',
    title: 'HashiCorp Terraform Associate',
    issuer: 'HashiCorp',
    description: 'Provision and manage infrastructure as code using Terraform across multiple cloud providers.',
    image: 'https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=600&q=80',
    tags: ['Terraform', 'IaC', 'DevOps'],
    category: 'technical',
    issuedAt: '2024-08-22',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'python-pcap',
    title: 'PCAP Python Certified',
    issuer: 'Python Institute',
    description: 'Proficiency in Python programming covering data structures, OOP, and standard libraries.',
    image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&q=80',
    tags: ['Python', 'Programming', 'Certification'],
    category: 'technical',
    issuedAt: '2024-07-15',
    link: '#',
    linkText: 'Credencial →',
  },

  // ── Leadership ──
  {
    id: 'pmp',
    title: 'Project Management Professional',
    issuer: 'PMI',
    description: 'Lead and direct projects, manage teams, and deliver results within scope and budget.',
    image: 'https://images.unsplash.com/photo-1553877522-43269d4ea984?w=600&q=80',
    tags: ['Project Management', 'Agile', 'Leadership'],
    category: 'otros',
    issuedAt: '2025-08-12',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'csm',
    title: 'Certified ScrumMaster',
    issuer: 'Scrum Alliance',
    description: 'Facilitate Scrum events, coach teams, and remove impediments in agile environments.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&q=80',
    tags: ['Scrum', 'Agile', 'Facilitation'],
    category: 'otros',
    issuedAt: '2025-06-25',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'six-sigma-green-belt',
    title: 'Six Sigma Green Belt',
    issuer: 'ASQ',
    description: 'Apply DMAIC methodology to improve processes, reduce defects, and optimize quality.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    tags: ['Quality', 'Process', 'DMAIC'],
    category: 'otros',
    issuedAt: '2025-04-08',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'itil-foundation',
    title: 'ITIL Foundation',
    issuer: 'AXELOS',
    description: 'Align IT services with business strategy using ITIL best practices and lifecycle management.',
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=600&q=80',
    tags: ['ITIL', 'Service Management', 'Governance'],
    category: 'otros',
    issuedAt: '2025-02-17',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'certified-manager',
    title: 'Certified Manager (CM)',
    issuer: 'ICM',
    description: 'Develop strategic vision, lead organizational change, and drive high-performance teams.',
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&q=80',
    tags: ['Management', 'Strategy', 'Leadership'],
    category: 'otros',
    issuedAt: '2024-11-30',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'safe-practitioner',
    title: 'SAFe 5 Practitioner',
    issuer: 'Scaled Agile',
    description: 'Apply Lean-Agile principles at enterprise scale and coordinate Agile Release Trains.',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600&q=80',
    tags: ['SAFe', 'Agile', 'Enterprise'],
    category: 'otros',
    issuedAt: '2024-09-05',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'lean-six-sigma-black-belt',
    title: 'Lean Six Sigma Black Belt',
    issuer: 'IASSC',
    description: 'Lead complex improvement projects, apply advanced statistical analysis, and drive cultural change.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600&q=80',
    tags: ['Lean', 'Six Sigma', 'Quality'],
    category: 'otros',
    issuedAt: '2024-07-20',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'change-management',
    title: 'Certified Change Manager',
    issuer: 'Prosci',
    description: 'Apply structured change management methodologies to drive organizational transformation.',
    image: 'https://images.unsplash.com/photo-1542744173-8e7e53415bb0?w=600&q=80',
    tags: ['Change Management', 'ADKAR', 'Transformation'],
    category: 'otros',
    issuedAt: '2024-05-12',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'coaching-certification',
    title: 'Professional Coach Certification',
    issuer: 'ICF',
    description: 'Develop coaching skills to empower teams, enhance performance, and foster professional growth.',
    image: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=600&q=80',
    tags: ['Coaching', 'Mentoring', 'Leadership'],
    category: 'otros',
    issuedAt: '2024-03-08',
    link: '#',
    linkText: 'Credencial →',
  },
  {
    id: 'conflict-resolution',
    title: 'Conflict Resolution Specialist',
    issuer: 'Mediation Institute',
    description: 'Master negotiation and mediation strategies to resolve disputes and build consensus.',
    image: 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?w=600&q=80',
    tags: ['Mediation', 'Negotiation', 'Leadership'],
    category: 'otros',
    issuedAt: '2024-01-25',
    link: '#',
    linkText: 'Credencial →',
  },
];

export function getCertifications(): Certification[] {
  return certificationsData;
}

export function getCertificationsByCategory(category: 'technical' | 'otros'): Certification[] {
  return certificationsData.filter(c => c.category === category);
}
