import type { Certification } from '../domain/certification';

const certificationsData: Certification[] = [
  // ── Technical ──
  {
    id: 'ccna1-introduction-to-networks',
    title: 'CCNA: Introduction to Networks',
    issuer: 'Cisco Networking Academy',
    description: 'Network fundamentals, IP addressing, OSI and TCP/IP models, basic router and switch configuration.',
    image: '/certificates-tech/thumbnails/AndryCaceres-CCNA1_CR1_2024-certificate.jpg',
    tags: ['Cisco', 'Networking', 'CCNA', 'Routing'],
    category: 'technical',
    issuedAt: '2024-01-01',
    link: '/certificates-tech/AndryCaceres-CCNA1_CR1_2024-certificate.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'fiti-2024',
    title: 'IT Fundamentals (FITI)',
    issuer: 'Cisco Networking Academy',
    description: 'IT Fundamentals, hardware, software, security and problem-solving.',
    image: '/certificates-tech/thumbnails/AndryCaceres-FITI%202024-certificate.jpg',
    tags: ['IT', 'Fundamentals', 'Cisco'],
    category: 'technical',
    issuedAt: '2024-01-01',
    link: '/certificates-tech/AndryCaceres-FITI%202024-certificate.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'ucsm-email-cert',
    title: 'CCNA: Enterprise Networking, Security, and Automation',
    issuer: 'Universidad Católica de Santa María',
    description: 'Enterprise networking, security, and automation concepts.',
    image: '/certificates-tech/thumbnails/Andry_Caceres_andry.caceres@ucsm.edu.pe.jpg',
    tags: ['CCNA', 'Enterprise', 'Networking', 'Security', 'Cisco'],
    category: 'technical',
    issuedAt: '2025-03-03',
    link: '/certificates-tech/Andry_Caceres_andry.caceres@ucsm.edu.pe.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'ccna-switching-routing-wireless',
    title: 'CCNA: Switching, Routing, and Wireless Essentials',
    issuer: 'Cisco Networking Academy',
    description: 'VLAN switching, routing protocols, wireless networks and enterprise configuration.',
    image: '/certificates-tech/thumbnails/CCNA-_Switching-_Routing-_and_Wireless_Essentials_certificate_andry-caceres-ucsm-edu-pe_74f70f19-6622-432c-b6c7-2afe34243a38.jpg',
    tags: ['Cisco', 'Switching', 'Routing', 'Wireless', 'CCNA'],
    category: 'technical',
    issuedAt: '2024-01-01',
    link: '/certificates-tech/CCNA-_Switching-_Routing-_and_Wireless_Essentials_certificate_andry-caceres-ucsm-edu-pe_74f70f19-6622-432c-b6c7-2afe34243a38.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'database-cert',
    title: 'Certification in Databases',
    issuer: 'Certiport',
    description: 'Design, implementation and administration of relational databases.',
    image: '/certificates-tech/thumbnails/databaseCert.jpg',
    tags: ['Database', 'SQL', 'Data'],
    category: 'technical',
    issuedAt: '2024-01-01',
    link: '/certificates-tech/databaseCert.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'javascript-essentials-1',
    title: 'JavaScript Essentials 1',
    issuer: 'Cisco Networking Academy',
    description: 'Fundamentals of JavaScript, syntax, control structures, functions and DOM events.',
    image: '/certificates-tech/thumbnails/JavaScriptEssentials1Update20250307-27-brff2i.jpg',
    tags: ['JavaScript', 'Programming', 'Web'],
    category: 'technical',
    issuedAt: '2025-03-07',
    link: '/certificates-tech/JavaScriptEssentials1Update20250307-27-brff2i.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'python-essentials-1',
    title: 'Python Essentials 1',
    issuer: 'Cisco Networking Academy / Python Institute',
    description: 'Fundamentals of Python, data types, control structures, functions and basic modules.',
    image: '/certificates-tech/thumbnails/Python_Essentials_1_Badge20250107-27-25u25c.jpg',
    tags: ['Python', 'Programming', 'Fundamentals'],
    category: 'technical',
    issuedAt: '2025-01-07',
    link: '/certificates-tech/Python_Essentials_1_Badge20250107-27-25u25c.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'python-essentials-2',
    title: 'Python Essentials 2',
    issuer: 'Cisco Networking Academy / Python Institute',
    description: 'Object-oriented programming, file handling, advanced modules and standard libraries.',
    image: '/certificates-tech/thumbnails/Python_Essentials_2_Badge20250107-27-2uhpib.jpg',
    tags: ['Python', 'OOP', 'Advanced'],
    category: 'technical',
    issuedAt: '2025-01-07',
    link: '/certificates-tech/Python_Essentials_2_Badge20250107-27-2uhpib.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'word-2019-associate',
    title: 'Microsoft Word 2019 Associate',
    issuer: 'Microsoft',
    description: 'Advanced Microsoft Word skills: formatting, styles, tables, references and automation.',
    image: '/certificates-tech/thumbnails/Word%202019%20Associate.jpg',
    tags: ['Microsoft', 'Office', 'Word'],
    category: 'technical',
    issuedAt: '2024-01-01',
    link: '/certificates-tech/Word%202019%20Associate.pdf',
    linkText: 'View certificate →',
  },

  // ── Participación & Otros ──
  {
    id: 'acnocios058',
    title: 'Responsibility in Action: Understanding and Implementing the SDGs',
    issuer: 'Universidad Católica de Santa María',
    description: 'Participation in workshop on sustainable development goals and responsible action.',
    image: '/certificates-otros/thumbnails/ACNOCIOS058.jpg',
    tags: ['Sustainable Development', 'SDGs'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/ACNOCIOS058.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'andry-caceres-quispe',
    title: 'Participation in the Global Game Jam 2025 at the Universidad Católica de San Pablo',
    issuer: 'Universidad Católica de San Pablo ACM Student Chapter',
    description: 'Participation and development of a video game within 48 hours.',
    image: '/certificates-otros/thumbnails/Andry%20C%C3%A1ceres%20Quispe.jpg',
    tags: ['GameJam', 'Video Games', 'Creativity'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/Andry%20C%C3%A1ceres%20Quispe.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'cumis-2026',
    title: 'Multidisciplinary University Research and Service Camp (CUMIS) 2026',
    issuer: 'Universidad Nacional de San Agustín SOCIEMA',
    description: 'University camp with medical students to conduct medical outreach and research for one week in high-risk communities',
    image: '/certificates-otros/thumbnails/ANDRY-CACERES_cumis2026.jpg',
    tags: ['Medical Outreach', 'Research', 'Community Service'],
    category: 'otros',
    issuedAt: '2026-01-01',
    link: '/certificates-otros/ANDRY-CACERES_cumis2026.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'ccrpuusa070',
    title: 'Challenges for a Healthy University',
    issuer: 'Universidad Católica de Santa María',
    description: 'Contest and submission of solutions to problems within the UCSM',
    image: '/certificates-otros/thumbnails/CCRPUUSA070.jpg',
    tags: ['University Challenges', 'Problem Solving', 'Innovation'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/CCRPUUSA070.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'eth-lima',
    title: 'ETH Lima',
    issuer: 'Ethereum',
    description: 'Participation in Ethereum Lima event, learning about blockchain technology and decentralized applications.',
    image: '/certificates-otros/thumbnails/CertificadoETHLima.jpg',
    tags: ['Blockchain', 'Ethereum', 'Web3'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/CertificadoETHLima.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'ctienrsu714',
    title: 'Student Initiatives in University Social Responsibility',
    issuer: 'Universidad Católica de Santa María',
    description: 'Participation in the course on student initiatives in university social responsibility, focusing on community engagement and social impact.',
    image: '/certificates-otros/thumbnails/CTIENRSU714.jpg',
    tags: ['Student Initiatives', 'Social Responsibility', 'Community Engagement'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/CTIENRSU714.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'game-jam-2026',
    title: 'Game Jam 2026',
    issuer: 'IGDA México Sur',
    description: 'Participation in game jam: development of video games in team during 48 hours.',
    image: '/certificates-otros/thumbnails/gameJam2026.jpg',
    tags: ['GameJam', 'Video Games', 'Creativity'],
    category: 'otros',
    issuedAt: '2026-01-01',
    link: '/certificates-otros/gameJam2026.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'vrinme24042',
    title: 'Practical, hands-on application development training program and startup mentoring focused on leadership',
    issuer: 'MW Coach kr & Universidad Católica de Santa María',
    description: 'Development of mobile applications and workshops of leadership.',
    image: '/certificates-otros/thumbnails/VRINME24042.jpg',
    tags: ['Research', 'Innovation', 'Leadership', 'Mobile Development'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/VRINME24042.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'innova-sur',
    title: 'Innova Sur 2024',
    issuer: 'Universidad Católica de Santa María',
    description: 'Hackathon for innovation and entrepreneurship.',
    image: '/certificates-otros/thumbnails/innova_sur.jpg',
    tags: ['Innovation', 'Hackathon', 'Regional'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/innova_sur.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'innovation-2025',
    title: 'Innovation Challlenge 2025',
    description: 'Innovation Contest.',
    issuer: 'Universidad Católica de Santa María',
    image: '/certificates-otros/thumbnails/innovation_2025.jpg',
    tags: ['Innovation', 'Contest', 'Entrepreneurship'],
    category: 'otros',
    issuedAt: '2025-01-01',
    link: '/certificates-otros/innovation_2025.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'jinis-2025',
    title: 'JINIS 2025',
    issuer: 'Universidad Católica de Santa María',
    description: 'Participation in Research and Innovation Day.',
    image: '/certificates-otros/thumbnails/jinis2025.jpg',
    tags: ['Research', 'Innovation', 'Workshop'],
    category: 'otros',
    issuedAt: '2025-01-01',
    link: '/certificates-otros/jinis2025.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'jini-2023',
    title: 'JINIS 2023',
    issuer: 'Universidad Católica de Santa María',
    description: 'Participation in Research and Innovation Day.',
    image: '/certificates-otros/thumbnails/JINI2023540.jpg',
    tags: ['Research', 'Innovation', 'Workshop'],
    category: 'otros',
    issuedAt: '2023-01-01',
    link: '/certificates-otros/JINI2023540.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'jini-2024',
    title: 'JINIS 2024',
    issuer: 'Universidad Católica de Santa María',
    description: 'Participation in Research and Innovation Day.',
    image: '/certificates-otros/thumbnails/JINI2024090.jpg',
    tags: ['Research', 'Innovation', 'Workshop'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/JINI2024090.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'nasa-space-apps',
    title: 'NASA Space Apps Challenge',
    issuer: 'NASA',
    description: 'Participation in the global NASA hackathon: development of innovative solutions for space and Earth challenges.',
    image: '/certificates-otros/thumbnails/NASA%20Space%20Apps%20Challenge%20Certificate.jpg',
    tags: ['NASA', 'Space', 'Hackathon', 'Innovation'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/NASA%20Space%20Apps%20Challenge%20Certificate.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'vrincha050',
    title: 'Innovation Challenge 2024',
    issuer: 'Universidad Católica de Santa María',
    description: 'Participation in the Innovation Challenge 2024, presenting innovative solutions to real-world problems.',
    image: '/certificates-otros/thumbnails/VRINNCHA050.jpg',
    tags: ['Research', 'Innovation', 'Challenge'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/VRINNCHA050.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'ideathon',
    title: 'Emprende Cup',
    issuer: 'Universidad Católica de Santa María',
    description: 'Participation in the innovation and entrepreneurship competition.',
    image: '/certificates-otros/thumbnails/ideaton.jpg',
    tags: ['Ideation', 'Innovation', 'Entrepreneurship'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/ideaton.pdf',
    linkText: 'View certificate →',
  },
  {
    id: 'acm',
    title: 'ACM Chair Role Certificate',
    issuer: 'Association for Computing Machinery',
    description: 'Participation and recognition in ACM activities.',
    image: '/certificates-otros/thumbnails/acm.jpg',
    tags: ['ACM', 'Computing', 'Recognition'],
    category: 'otros',
    issuedAt: '2024-01-01',
    link: '/certificates-otros/acm.pdf',
    linkText: 'View certificate →',
  },
];

export function getCertifications(): Certification[] {
  return certificationsData;
}

export function getCertificationsByCategory(category: 'technical' | 'otros'): Certification[] {
  return certificationsData.filter(c => c.category === category);
}
